export const DspFDSWebLegacyThemeUsage = {
  light: {
    accent: '#0866FF',
    'blue-link': '#0064D1',
    'fb-wordmark': '#0866FF',
    'filter-accent': 'invert(19%) sepia(70%) saturate(5671%) hue-rotate(203deg) brightness(96%) contrast(101%)',
    'filter-primary-accent': 'invert(27%) sepia(95%) saturate(3116%) hue-rotate(212deg) brightness(99%) contrast(105%)',
    'focus-ring-blue': '#0866FF',
    'hosted-view-selected-state': '#EBF5FF',
    'input-label-color-highlighted': '#0064D1',
    'primary-button-background': '#0866FF',
    'primary-deemphasized-button-background': '#EBF5FF',
    'primary-deemphasized-button-text': '#0064D1',
    'progress-ring-blue-background': 'rgba(8, 102, 255, 0.2)',
    'progress-ring-blue-foreground': '#0866FF',
    'text-highlight': 'rgba(8, 102, 255, 0.2)',
    'toggle-active-background': '#EBF5FF',
    'toggle-active-icon': '#0064D1',
    'toggle-active-text': '#0064D1',
    'action-tile-radius': '16px',
    'attachment-footer-background': '#F8F9FB',
    'background-deemphasized': '#F2F4F7',
    'base-cherry': '#FB3C44',
    'base-grape': '#7D74FF',
    'base-lemon': '#F9CF00',
    'base-lime': '#3FBB46',
    'base-pink': '#FA61BA',
    'base-teal': '#14B898',
    'border-ui-emphasis': '#E2E5E9',
    'bottom-sheet-corner-radius': '20px',
    'button-corner-radius': '8px',
    'card-background': '#FFFFFF',
    'card-background-flat': '#F8F9FB',
    'card-corner-radius': '12px',
    'card-large-corner-radius': '16px',
    'card-small-corner-radius': '12px',
    'comment-background': '#F0F2F5',
    'comment-bubble': '16px',
    'comment-threading-lines': '#E2E5E9',
    'dialog-corner-radius': '12px',
    'disabled-button-background': '#E2E5E9',
    'disabled-icon': '#B0B3B8',
    'disabled-text': '#B0B3B8',
    divider: '#D0D3D7',
    'divider-on-color': '#5C5E62',
    'event-date': '#DD2334',
    'fb-logo': '#0866FF',
    'fds-animation-enter-exit-in': 'cubic-bezier(0.14,1,0.34,1)',
    'fds-animation-enter-exit-out': 'cubic-bezier(0.45,0.1,0.2,1)',
    'fds-animation-expand-collapse-in': 'cubic-bezier(0.17,0.17,0,1)',
    'fds-animation-expand-collapse-out': 'cubic-bezier(0.17,0.17,0,1)',
    'fds-animation-fade-in': 'cubic-bezier(0,0,1,1)',
    'fds-animation-fade-out': 'cubic-bezier(0,0,1,1)',
    'fds-animation-move-in': 'cubic-bezier(0.17,0.17,0,1)',
    'fds-animation-move-out': 'cubic-bezier(0.17,0.17,0,1)',
    'fds-animation-passive-move-in': 'cubic-bezier(0.5,0,0.1,1)',
    'fds-animation-passive-move-out': 'cubic-bezier(0.5,0,0.1,1)',
    'fds-animation-quick-move-in': 'cubic-bezier(0.1,0.9,0.2,1)',
    'fds-animation-quick-move-out': 'cubic-bezier(0.1,0.9,0.2,1)',
    'fds-animation-swap-shuffle-in': 'cubic-bezier(0.14,1,0.34,1)',
    'fds-animation-swap-shuffle-out': 'cubic-bezier(0.45,0.1,0.2,1)',
    'fds-duration-extra-extra-short-in': '100ms',
    'fds-duration-extra-extra-short-out': '100ms',
    'fds-duration-extra-long-in': '1000ms',
    'fds-duration-extra-long-out': '1000ms',
    'fds-duration-extra-short-in': '200ms',
    'fds-duration-extra-short-out': '150ms',
    'fds-duration-long-in': '500ms',
    'fds-duration-long-out': '350ms',
    'fds-duration-medium-in': '400ms',
    'fds-duration-medium-out': '350ms',
    'fds-duration-none': '0ms',
    'fds-duration-short-in': '280ms',
    'fds-duration-short-out': '200ms',
    'fds-fast': '200ms',
    'fds-slow': '400ms',
    'glimmer-base-opaque': '#979A9F',
    'glimmer-high-contrast-base-opaque': '#65686C',
    'glimmer-opacity-high-contrast-max': '1',
    'glimmer-opacity-high-contrast-min': '0.08',
    'glimmer-opacity-max': '0.5',
    'glimmer-opacity-min': '0.15',
    'infochip-large-radius': '8px',
    'infochip-medium-radius': '4px',
    'infochip-small-radius': '4px',
    'input-border-width': '1px',
    'input-corner-radius': '12px',
    'last-active-state-background': '#F2FCF0',
    'last-active-state-text': '#1E5E21',
    'link-on-media': '#FFFFFF',
    'list-cell-corner-radius': '8px',
    'list-cell-min-height': '44px',
    'listcell-inset-radius': '16px',
    'media-corner-radius': '12px',
    'media-hovered': 'rgba(70, 72, 75, 0.15)',
    'media-inner-border': 'rgba(0, 0, 0, 0.1)',
    'media-large-corner-radius': '16px',
    'media-pressed': 'rgba(70, 72, 75, 0.35)',
    'media-small-corner-radius': '12px',
    'nav-bar-background': '#FFFFFF',
    negative: '#DD2334',
    'negative-background': '#FFE3DE',
    'new-notification-background': '#E7F3FF',
    'non-media-pressed': 'rgba(70, 72, 75, 0.15)',
    'non-media-pressed-on-dark': 'rgba(255, 255, 255, 0.3)',
    'notification-badge': '#DD2334',
    'overlay-on-media': 'rgba(0, 0, 0, 0.8)',
    'placeholder-icon': '#65686C',
    'placeholder-image': '#979A9F',
    'placeholder-text': '#65686C',
    'placeholder-text-on-media': 'rgba(255, 255, 255, 0.8)',
    'popover-background': '#FFFFFF',
    positive: '#24832C',
    'positive-deemphasized': '#F2FCF0',
    'primary-button-background-on-color': '#FFFFFF',
    'primary-button-background-on-media': '#FFFFFF',
    'primary-button-icon': '#FFFFFF',
    'primary-button-icon-on-color': '#000000',
    'primary-button-icon-on-media': '#080809',
    'primary-button-text': '#FFFFFF',
    'primary-button-text-on-media': '#080809',
    'primary-deemphasized-button-icon': '#0064D1',
    'primary-icon': '#080809',
    'primary-icon-on-media': '#FFFFFF',
    'primary-text': '#080809',
    'primary-text-on-color': '#FFFFFF',
    'primary-text-on-media': '#FFFFFF',
    'progress-ring-disabled-background': 'rgba(176, 179, 184, 0.2)',
    'progress-ring-disabled-foreground': '#B0B3B8',
    'progress-ring-neutral-background': 'rgba(0, 0, 0, 0.2)',
    'progress-ring-neutral-foreground': '#000000',
    'progress-ring-on-media-background': 'rgba(255, 255, 255, 0.2)',
    'progress-ring-on-media-foreground': '#FFFFFF',
    'radio-border-width': '2px',
    'radio-checked-icon-size-large': '12px',
    'radio-checked-icon-size-medium': '12px',
    'radio-size-large': '24px',
    'radio-size-medium': '20px',
    'rating-star-active': '#E0761A',
    'rating-star-active-on-color': '#FFFFFF',
    'rating-star-active-on-media': '#FFFFFF',
    'reaction-anger': '#DD2334',
    'reaction-haha': '#887000',
    'reaction-like': '#0866FF',
    'reaction-love': '#DD2334',
    'reaction-sorry': '#887000',
    'reaction-support': '#887000',
    'reaction-wow': '#887000',
    'reshare-radius': '16px',
    'secondary-button-background': '#E2E5E9',
    'secondary-button-background-floating': '#FFFFFF',
    'secondary-button-background-on-color': 'rgba(255, 255, 255, 0.15)',
    'secondary-button-background-on-dark': 'rgba(28, 28, 29, 0.6)',
    'secondary-button-background-on-media': 'rgba(28, 28, 29, 0.6)',
    'secondary-button-icon-on-media': '#FFFFFF',
    'secondary-button-pressed': 'rgba(0, 0, 0, 0.05)',
    'secondary-button-stroke': 'rgba(0, 0, 0, 0)',
    'secondary-button-text': '#080809',
    'secondary-icon': '#65686C',
    'secondary-icon-on-color': 'rgba(255, 255, 255, 0.9)',
    'secondary-text': '#65686C',
    'secondary-text-on-color': 'rgba(255, 255, 255, 0.9)',
    'secondary-text-on-media': 'rgba(255, 255, 255, 0.8)',
    'story-seen': '#84878B',
    'story-unseen': '#0866FF',
    'surface-background': '#FFFFFF',
    'switch-unchecked-background-color': '#8F9297',
    'text-badge-corner-radius': '4px',
    'text-badge-padding-horizontal': '6px',
    'text-badge-padding-vertical': '6px',
    'text-input-active-text': '#0064D1',
    'text-input-caption-margin-top': '10px',
    'text-input-multi-padding-between-text-scrollbar': '20px',
    'text-input-multi-padding-scrollbar': '16px',
    'text-input-padding-vertical': '12px',
    'toast-addon-padding-horizontal': '6px',
    'toast-addon-padding-vertical': '6px',
    'toast-container-padding-horizontal': '10px',
    'toast-container-padding-vertical': '16px',
    'toast-corner-radius': '8px',
    'tooltip-background': 'rgba(255, 255, 255, 0.8)',
    'tooltip-corner-radius': '12px',
    warning: '#AF8F00',
    wash: '#C9CCD1',
    'web-wash': '#F2F4F7',
  },
  dark: {
    accent: '#0866FF',
    'blue-link': '#5AA7FF',
    'filter-accent': 'invert(74%) sepia(14%) saturate(7129%) hue-rotate(185deg) brightness(102%) contrast(101%)',
    'filter-primary-accent': 'invert(27%) sepia(95%) saturate(3116%) hue-rotate(212deg) brightness(99%) contrast(105%)',
    'focus-ring-blue': '#1D85FC',
    'hosted-view-selected-state': 'rgba(29, 133, 252, 0.1)',
    'input-label-color-highlighted': '#3E93F8',
    'primary-button-background': '#0866FF',
    'primary-deemphasized-button-background': 'rgba(29, 133, 252, 0.2)',
    'primary-deemphasized-button-text': '#75B6FF',
    'progress-ring-blue-background': 'rgba(8, 102, 255, 0.2)',
    'progress-ring-blue-foreground': '#0866FF',
    'text-highlight': 'rgba(29, 133, 252, 0.45)',
    'toggle-active-background': '#1D85FC',
    'action-tile-radius': '16px',
    'attachment-footer-background': 'rgba(255, 255, 255, 0.1)',
    'background-deemphasized': 'rgba(255, 255, 255, 0.1)',
    'base-cherry': '#FB3C44',
    'base-grape': '#7D74FF',
    'base-lemon': '#F9CF00',
    'base-lime': '#3FBB46',
    'base-pink': '#FA61BA',
    'base-teal': '#14B898',
    'border-ui-emphasis': 'rgba(255, 255, 255, 0.05)',
    'bottom-sheet-corner-radius': '20px',
    'button-corner-radius': '8px',
    'card-background': '#252728',
    'card-background-flat': '#333334',
    'card-corner-radius': '12px',
    'card-large-corner-radius': '16px',
    'card-small-corner-radius': '12px',
    'comment-background': '#333334',
    'comment-bubble': '16px',
    'comment-threading-lines': '#46484B',
    'dialog-corner-radius': '12px',
    'disabled-button-background': 'rgba(255, 255, 255, 0.1)',
    'disabled-icon': '#6F7276',
    'disabled-text': '#6F7276',
    divider: '#65686C',
    'divider-on-color': '#5C5E62',
    'event-date': '#DD2334',
    'fb-logo': '#0866FF',
    'fb-wordmark': '#FFFFFF',
    'fds-animation-enter-exit-in': 'cubic-bezier(0.14,1,0.34,1)',
    'fds-animation-enter-exit-out': 'cubic-bezier(0.45,0.1,0.2,1)',
    'fds-animation-expand-collapse-in': 'cubic-bezier(0.17,0.17,0,1)',
    'fds-animation-expand-collapse-out': 'cubic-bezier(0.17,0.17,0,1)',
    'fds-animation-fade-in': 'cubic-bezier(0,0,1,1)',
    'fds-animation-fade-out': 'cubic-bezier(0,0,1,1)',
    'fds-animation-move-in': 'cubic-bezier(0.17,0.17,0,1)',
    'fds-animation-move-out': 'cubic-bezier(0.17,0.17,0,1)',
    'fds-animation-passive-move-in': 'cubic-bezier(0.5,0,0.1,1)',
    'fds-animation-passive-move-out': 'cubic-bezier(0.5,0,0.1,1)',
    'fds-animation-quick-move-in': 'cubic-bezier(0.1,0.9,0.2,1)',
    'fds-animation-quick-move-out': 'cubic-bezier(0.1,0.9,0.2,1)',
    'fds-animation-swap-shuffle-in': 'cubic-bezier(0.14,1,0.34,1)',
    'fds-animation-swap-shuffle-out': 'cubic-bezier(0.45,0.1,0.2,1)',
    'fds-duration-extra-extra-short-in': '100ms',
    'fds-duration-extra-extra-short-out': '100ms',
    'fds-duration-extra-long-in': '1000ms',
    'fds-duration-extra-long-out': '1000ms',
    'fds-duration-extra-short-in': '200ms',
    'fds-duration-extra-short-out': '150ms',
    'fds-duration-long-in': '500ms',
    'fds-duration-long-out': '350ms',
    'fds-duration-medium-in': '400ms',
    'fds-duration-medium-out': '350ms',
    'fds-duration-none': '0ms',
    'fds-duration-short-in': '280ms',
    'fds-duration-short-out': '200ms',
    'fds-fast': '200ms',
    'fds-slow': '400ms',
    'glimmer-base-opaque': '#FFFFFF',
    'glimmer-high-contrast-base-opaque': '#FFFFFF',
    'glimmer-opacity-high-contrast-max': '0.48',
    'glimmer-opacity-high-contrast-min': '0.1',
    'glimmer-opacity-max': '0.58',
    'glimmer-opacity-min': '0.15',
    'infochip-large-radius': '8px',
    'infochip-medium-radius': '4px',
    'infochip-small-radius': '4px',
    'input-border-width': '1px',
    'input-corner-radius': '12px',
    'last-active-state-background': '#152B14',
    'last-active-state-text': '#90E78A',
    'link-on-media': '#FFFFFF',
    'list-cell-corner-radius': '8px',
    'list-cell-min-height': '44px',
    'listcell-inset-radius': '16px',
    'media-corner-radius': '12px',
    'media-hovered': 'rgba(255, 255, 255, 0.15)',
    'media-inner-border': 'rgba(255, 255, 255, 0.05)',
    'media-large-corner-radius': '16px',
    'media-pressed': 'rgba(255, 255, 255, 0.3)',
    'media-small-corner-radius': '12px',
    'nav-bar-background': '#252728',
    negative: '#FF7C74',
    'negative-background': 'rgba(185, 24, 40, 0.2)',
    'new-notification-background': 'rgba(45, 136, 255, 0.1)',
    'non-media-pressed': 'rgba(255, 255, 255, 0.2)',
    'non-media-pressed-on-dark': 'rgba(255, 255, 255, 0.3)',
    'notification-badge': '#DD2334',
    'overlay-on-media': 'rgba(0, 0, 0, 0.8)',
    'placeholder-icon': '#B0B3B8',
    'placeholder-image': '#979A9F',
    'placeholder-text': '#B0B3B8',
    'placeholder-text-on-media': 'rgba(255, 255, 255, 0.8)',
    'popover-background': '#3B3C3E',
    positive: '#3FBB46',
    'positive-deemphasized': '#121F10',
    'primary-button-background-on-color': '#FFFFFF',
    'primary-button-background-on-media': '#FFFFFF',
    'primary-button-icon': '#FFFFFF',
    'primary-button-icon-on-color': '#000000',
    'primary-button-icon-on-media': '#080809',
    'primary-button-text': '#FFFFFF',
    'primary-button-text-on-media': '#080809',
    'primary-deemphasized-button-icon': '#75B6FF',
    'primary-icon': '#E2E5E9',
    'primary-icon-on-media': '#FFFFFF',
    'primary-text': '#E2E5E9',
    'primary-text-on-color': '#FFFFFF',
    'primary-text-on-media': '#FFFFFF',
    'progress-ring-disabled-background': 'rgba(111, 114, 118, 0.2)',
    'progress-ring-disabled-foreground': '#6F7276',
    'progress-ring-neutral-background': 'rgba(255, 255, 255, 0.2)',
    'progress-ring-neutral-foreground': '#FFFFFF',
    'progress-ring-on-media-background': 'rgba(255, 255, 255, 0.2)',
    'progress-ring-on-media-foreground': '#FFFFFF',
    'radio-border-width': '2px',
    'radio-checked-icon-size-large': '12px',
    'radio-checked-icon-size-medium': '12px',
    'radio-size-large': '24px',
    'radio-size-medium': '20px',
    'rating-star-active': '#FF9A42',
    'rating-star-active-on-color': '#FFFFFF',
    'rating-star-active-on-media': '#FFFFFF',
    'reaction-anger': '#FF5757',
    'reaction-haha': '#F9CF00',
    'reaction-like': '#3E93F8',
    'reaction-love': '#FF5757',
    'reaction-sorry': '#F9CF00',
    'reaction-support': '#F9CF00',
    'reaction-wow': '#F9CF00',
    'reshare-radius': '16px',
    'secondary-button-background': 'rgba(255, 255, 255, 0.1)',
    'secondary-button-background-floating': '#46484B',
    'secondary-button-background-on-color': 'rgba(255, 255, 255, 0.15)',
    'secondary-button-background-on-dark': 'rgba(28, 28, 29, 0.6)',
    'secondary-button-background-on-media': 'rgba(28, 28, 29, 0.6)',
    'secondary-button-icon-on-media': '#FFFFFF',
    'secondary-button-pressed': 'rgba(255, 255, 255, 0.2)',
    'secondary-button-stroke': 'rgba(0, 0, 0, 0)',
    'secondary-button-text': '#E8EAEE',
    'secondary-icon': '#B0B3B8',
    'secondary-icon-on-color': 'rgba(255, 255, 255, 0.9)',
    'secondary-text': '#B0B3B8',
    'secondary-text-on-color': 'rgba(255, 255, 255, 0.9)',
    'secondary-text-on-media': 'rgba(255, 255, 255, 0.8)',
    'story-seen': '#84878B',
    'story-unseen': '#0866FF',
    'surface-background': '#252728',
    'switch-unchecked-background-color': '#6F7276',
    'text-badge-corner-radius': '4px',
    'text-badge-padding-horizontal': '6px',
    'text-badge-padding-vertical': '6px',
    'text-input-active-text': '#3E93F8',
    'text-input-caption-margin-top': '10px',
    'text-input-multi-padding-between-text-scrollbar': '20px',
    'text-input-multi-padding-scrollbar': '16px',
    'text-input-padding-vertical': '12px',
    'toast-addon-padding-horizontal': '6px',
    'toast-addon-padding-vertical': '6px',
    'toast-container-padding-horizontal': '10px',
    'toast-container-padding-vertical': '16px',
    'toast-corner-radius': '8px',
    'toggle-active-icon': '#FFFFFF',
    'toggle-active-text': '#FFFFFF',
    'tooltip-background': 'rgba(0, 0, 0, 0.8)',
    'tooltip-corner-radius': '12px',
    warning: '#AF8F00',
    wash: '#1C1C1D',
    'web-wash': '#1C1C1D',
  },
};
